### ISSUE TITLE
Send dummy request

### ISSUE THREAD

**Issue by tamht298** [cescoffier/quarkus-kafka-and-avro#5]
I have an issue when I try to post request: 
```
curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"title":"The Shawshank Redemption","year":1994}' \
  http://localhost:8080/movies
```
```
2021-01-19 11:42:16,032 ERROR [io.sma.rea.mes.kafka] (vert.x-eventloop-thread-14) SRMSG18206: Unable to write to Kafka from channel movies (topic: movies): javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request: org.apache.http.NoHttpResponseException: localhost:8081 failed to respond
        at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.invoke(ManualClosingApacheHttpClient43Engine.java:287)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:488)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:149)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:112)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
        at com.sun.proxy.$Proxy56.getArtifactMetaData(Unknown Source)
        at jdk.internal.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:147)
        at com.sun.proxy.$Proxy57.getArtifactMetaData(Unknown Source)
        at jdk.internal.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.apicurio.registry.client.GenericClient$ServiceProxy.invoke(GenericClient.java:206)
        at com.sun.proxy.$Proxy45.getArtifactMetaData(Unknown Source)
        at io.apicurio.registry.utils.serde.strategy.GetOrCreateIdStrategy.initialLookup(GetOrCreateIdStrategy.java:29)
        at io.apicurio.registry.utils.serde.strategy.AbstractCrudIdStrategy.findId(AbstractCrudIdStrategy.java:50)
        at io.apicurio.registry.utils.serde.AbstractKafkaSerializer.serialize(AbstractKafkaSerializer.java:66)
        at org.apache.kafka.common.serialization.Serializer.serialize(Serializer.java:62)
        at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:902)
        at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:862)
        at io.vertx.kafka.client.producer.impl.KafkaWriteStreamImpl.lambda$send$4(KafkaWriteStreamImpl.java:93)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.http.NoHttpResponseException: localhost:8081 failed to respond
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.invoke(ManualClosingApacheHttpClient43Engine.java:268)
```

**Comment by cescoffier** [comment]
The schema registry is not available. Use the provided docker-compose file that starts it.

**Comment by tamht298** [comment]
My registry's still running, I used docker-compose for it.
 
```
CONTAINER ID   IMAGE                                        COMMAND                  CREATED       STATUS       PORTS                                             NAMES
d520171018a5   apicurio/apicurio-registry-mem:1.2.2.Final   "/deployments/run-ja…"   2 hours ago   Up 2 hours   8778/tcp, 9779/tcp, 0.0.0.0:8081->8080/tcp        avro-with-quarkus_schema-registry_1
6ea9459ba704   strimzi/kafka:0.11.3-kafka-2.1.0             "sh -c 'bin/kafka-se…"   2 hours ago   Up 2 hours   9091/tcp, 9404/tcp, 0.0.0.0:9092->9092/tcp        avro-with-quarkus_kafka_1
3cd306bad4c5   strimzi/kafka:0.11.3-kafka-2.1.0             "sh -c 'bin/zookeepe…"   2 hours ago   Up 2 hours   9091-9092/tcp, 0.0.0.0:2181->2181/tcp, 9404/tcp   avro-with-quarkus_zookeeper_1
```

**Comment by cescoffier** [comment]
So, check why "0.0.0.0:8081->8080/tcp" is not working properly. 
Check also the log of the container.

**Comment by tamht298** [comment]
Thanks for supporting, I have problem with conflict port of registry schema
